
project_id = "nyebwdvhkgiumqswbrfb"

[api]
port = 54321

[db]
port = 54322

[auth]
site_url = "http://localhost:54321"
additional_redirect_urls = []
jwt_expiry = 3600
jwt_secret = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZWJ3ZHZoa2dpdW1xc3dicmZiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjMxOTgwMywiZXhwIjoyMDcxODk1ODAzfQ.QbE0qvTMK6wJ9AH4kCP10yktmOIQ9xPLjUjml1EE93Y"

[functions.create-payment-intent]
enabled = true
verify_jwt = false
import_map = "./functions/create-payment-intent/deno.json"
entrypoint = "./functions/create-payment-intent/index.ts"
